### ISSUE TITLE
Plugin is added as jq but binary is gojq

### ISSUE THREAD

**Issue by chrisjohnson** [jimmidyson/asdf-gojq#1]
The README suggests calling the plugin `jq` during install e.g. `asdf plugin-add jq https://github.com/jimmidyson/asdf-gojq.git` but then once it's added and you install jq `asdf install jq latest` then you can't find the jq binary because it gets installed as gojq

I did the following:

```
cp ~/.asdf/shims/gojq ~/.asdf/shims/jq
```

But I wasn't sure if there was a better way to handle this during the plugin's install step. Any thoughts?

**Comment by jimmidyson** [comment]
Oops sorry that's a typo in the readme. It should be `asdf plugin add gojq https://github.com/jimmidyson/asdf-gojq.git`

**Comment by chrisjohnson** [comment]
Fwiw the readme isn't corrected yet

**Comment by jimmidyson** [comment]
Sorry I'll get that updated today.

Btw this plug-in is in the official community index so you can actually just run `aadf plugin add gojq` without the URL and it will resolve from the community index.
